// dummy-agent registers on the bus with a configurable capability,
// accepts any request, and replies with a canned report. Useful for
// testing the concierge end-to-end without real specialist agents.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"strings"
	"time"

	"github.com/joelkehle/techtransfer-agency/internal/busclient"
)

func main() {
	busURL := flag.String("bus-url", "http://localhost:8090", "bus base URL")
	agentID := flag.String("id", "dummy-patent-screen", "agent ID")
	secret := flag.String("secret", "dummy-secret", "agent secret")
	capability := flag.String("capability", "patent-screen", "capability to advertise")
	flag.Parse()

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	client := busclient.NewClient(*busURL)

	// Register.
	if err := client.RegisterAgent(ctx, *agentID, *secret, []string{*capability}); err != nil {
		log.Fatalf("register: %v", err)
	}
	log.Printf("registered as %s with capability %s on %s", *agentID, *capability, *busURL)

	// Heartbeat.
	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			case <-time.After(60 * time.Second):
				_ = client.RegisterAgent(ctx, *agentID, *secret, []string{*capability})
			}
		}
	}()

	// Poll loop.
	cursor := 0
	for {
		select {
		case <-ctx.Done():
			log.Println("shutting down")
			return
		default:
		}

		events, next, err := client.PollInbox(ctx, *agentID, *secret, cursor, 30)
		if err != nil {
			log.Printf("poll: %v", err)
			time.Sleep(2 * time.Second)
			continue
		}
		cursor = next

		for _, evt := range events {
			log.Printf("received %s from %s: %s", evt.Type, evt.From, truncate(evt.Body, 100))

			// Ack.
			if err := client.Ack(ctx, *agentID, *secret, evt.MessageID, "accepted", "processing"); err != nil {
				log.Printf("ack: %v", err)
				continue
			}

			// Progress.
			_ = client.Event(ctx, *agentID, *secret, evt.MessageID, "progress", "analyzing document...", nil)
			time.Sleep(2 * time.Second)
			_ = client.Event(ctx, *agentID, *secret, evt.MessageID, "progress", "generating report...", nil)
			time.Sleep(1 * time.Second)

			// Final event.
			_ = client.Event(ctx, *agentID, *secret, evt.MessageID, "final", "report complete", nil)

			// Send response back to sender.
			report := generateReport(*capability, evt.Body)
			_, err := client.SendMessage(
				ctx,
				*agentID,
				*secret,
				evt.From,
				evt.ConversationID,
				fmt.Sprintf("resp-%s", evt.MessageID),
				"response",
				report,
				nil,
				nil,
			)
			if err != nil {
				log.Printf("send response: %v", err)
			} else {
				log.Printf("sent report to %s", evt.From)
			}
		}
	}
}

func generateReport(capability, requestBody string) string {
	now := time.Now().Format("2006-01-02 15:04:05 MST")
	cap := strings.ReplaceAll(capability, "-", " ")
	cap = strings.Title(cap)

	return fmt.Sprintf(`%s Report
Generated: %s
Version: 1.0-dummy

Request: %s

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Summary:
This is a dummy report generated for testing the concierge submission
workflow. In production, this would be replaced by a real specialist
agent performing actual %s analysis.

Findings:
- Document was received and processed successfully
- All pipeline stages completed normally
- The submission portal is functioning correctly

Recommendation:
Replace this dummy agent with a real specialist implementation.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: This is a test report generated by a dummy agent.
It does not contain real analysis.
`, cap, now, truncate(requestBody, 200), strings.ToLower(cap))
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
